#!/usr/bin/env bash
# This script extends previous excercise command and displays line containing the bash world, this allowing you to easilly get the PID of your Bash process
# You cannot use pgrep 
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
